// SPDX-FileCopyrightText: 2026 Bernd Zeimetz <bernd@bzed.de>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Package units is `dzo units sync` (§C5): it writes the systemd units dzo
// generates, the quadlet of every instance and the timers and services that
// run restarts, backups, update checks and the exporter, and removes the ones
// that no longer apply. Every generated file starts with a header, and only
// files with that header are ever removed. It also records which generations
// an instance's unit was written with, which is how a pending update is
// recognised: the cache has a newer generation than the running unit.
package units

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/bzed/dayz-server-operator/internal/config"
	"github.com/bzed/dayz-server-operator/internal/instance"
	"github.com/bzed/dayz-server-operator/internal/quadlet"
	"github.com/bzed/dayz-server-operator/internal/resolve"
	"github.com/bzed/dayz-server-operator/internal/site"
)

// Header starts every generated file; only files that have it are removed.
const Header = "# Generated by dzo (dzo units sync). Do not edit: changes are overwritten.\n"

// DefaultConfig is the config path units run with when nothing else is given.
const DefaultConfig = "/etc/dzo/config.yaml"

// Where a unit file goes.
type Dir int

// The two directories: quadlets (podman generates the service) and plain units.
const (
	Quadlet Dir = iota
	Systemd
)

// File is one generated unit file.
type File struct {
	Dir     Dir
	Name    string
	Content string
	Enable  string // unit to enable and start with it ("" for none)
	Hold    bool   // keep the file that is there: an update is pending (see Options.Deploy)
}

// Options say where and how units are generated.
type Options struct {
	Cfg        *config.Config
	DzoBin     string // what the units run
	ConfigPath string // passed as --config unless it is DefaultConfig
	QuadletDir string // ~/.config/containers/systemd
	UnitDir    string // ~/.config/systemd/user
	StatusDir  string // where dzo status --write puts its files, default /run/dzo/status
	// Deploy names the instances whose pending updates are deployed: their
	// unit is rewritten with the new generations. Any other instance with
	// updates pending keeps the unit it has, so that a crash restart or a
	// reboot never picks up a half-announced update. "*" deploys all.
	Deploy []string
}

func (o Options) deploys(name string) bool {
	for _, d := range o.Deploy {
		if d == name || d == "*" {
			return true
		}
	}
	return false
}

func (o Options) bin() string {
	if o.DzoBin == "" {
		return "/usr/bin/dzo"
	}
	return o.DzoBin
}

// cmd builds an ExecStart line.
func (o Options) cmd(args ...string) string {
	line := o.bin() + " " + strings.Join(args, " ")
	if o.ConfigPath != "" && o.ConfigPath != DefaultConfig {
		line += " --config " + o.ConfigPath
	}
	return line
}

// Calendar returns an OnCalendar expression that fires about every d.
func Calendar(d time.Duration) string {
	switch {
	case d <= 0:
		return "hourly"
	case d < time.Hour:
		if m := int(d / time.Minute); m >= 1 && 60%m == 0 {
			return fmt.Sprintf("*:0/%d", m)
		}
		return "hourly"
	default:
		if h := int(d / time.Hour); h < 24 && 24%h == 0 {
			if h == 1 {
				return "hourly"
			}
			return fmt.Sprintf("*-*-* 0/%d:00", h)
		}
		return "daily"
	}
}

// Gens are the generations an instance's unit was written with.
type Gens struct {
	Build string            `json:"build"`
	Mods  map[string]string `json:"mods"`
}

// GensOf returns the generations the resolved instance would be deployed with.
func GensOf(inst *resolve.Instance) Gens {
	g := Gens{Build: inst.Product.Build, Mods: map[string]string{}}
	for _, m := range inst.Mods {
		g.Mods[m.Name] = m.Generation
	}
	return g
}

func gensFile(runtimeDir string) string { return filepath.Join(runtimeDir, "generations.json") }

// Applied returns the generations the instance's unit was last written with.
func Applied(inst *resolve.Instance) (Gens, bool) {
	b, err := os.ReadFile(gensFile(inst.Paths.Runtime)) //nolint:gosec // dzo's own runtime dir
	if err != nil {
		return Gens{}, false
	}
	var g Gens
	if json.Unmarshal(b, &g) != nil {
		return Gens{}, false
	}
	return g, true
}

// Pending lists what changed in the cache since the unit was written: the
// server build (as "build") and the mods (by name), sorted.
func Pending(inst *resolve.Instance) []string {
	applied, ok := Applied(inst)
	if !ok {
		return nil // never deployed: nothing is "pending", the first start uses what is current
	}
	now := GensOf(inst)
	var out []string
	// A server build is pinned per instance: a newer installed build waits for `dzo instance upgrade`.
	if inst.Product.Latest != "" && inst.Product.Latest != inst.Product.Build {
		out = append(out, "build")
	}
	for name, gen := range now.Mods {
		if old, had := applied.Mods[name]; had && old != gen {
			out = append(out, name)
		}
	}
	sort.Strings(out)
	return out
}

// Record writes the generations of the instance's current unit.
func Record(inst *resolve.Instance) error {
	b, err := json.MarshalIndent(GensOf(inst), "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(inst.Paths.Runtime, 0o750); err != nil {
		return err
	}
	if err := writeAtomic(gensFile(inst.Paths.Runtime), append(b, '\n'), 0o640); err != nil {
		return err
	}
	// Pin the build the unit runs, so that a later `dzo product update` does not move the instance.
	if inst.Product.Build != "" {
		return writeAtomic(resolve.BuildPinFile(inst.Paths.Runtime), []byte(inst.Product.Build+"\n"), 0o640)
	}
	return nil
}

func generated(content string) string { return Header + content }

func timer(o Options, name, desc, exec string, calendar []string, persistent bool) []File {
	t := instance.TimerUnit{Name: name, Description: desc, ExecStart: exec, OnCalendar: calendar, Persistent: persistent}
	tm, _ := t.RenderTimer()
	sv, _ := t.RenderService()
	return []File{
		{Dir: Systemd, Name: name + ".timer", Content: generated(tm), Enable: name + ".timer"},
		{Dir: Systemd, Name: name + ".service", Content: generated(sv)},
	}
}

// ExporterUnit is the long-running exporter service.
func exporterUnit(o Options) File {
	return File{Dir: Systemd, Name: "dzo-exporter.service", Enable: "dzo-exporter.service", Content: generated(
		"[Unit]\nDescription=dzo exporter (/metrics and /status)\nAfter=network.target\n\n" +
			"[Service]\nExecStart=" + o.cmd("exporter") + "\nExecReload=/bin/kill -HUP $MAINPID\nRestart=on-failure\nRestartSec=5\n\n" +
			"[Install]\nWantedBy=default.target\n")}
}

// Desired returns the unit files of the whole installation, and warnings
// about instances that cannot be deployed yet.
func Desired(o Options, tree *site.Tree) (files []File, warnings []string, err error) {
	minCheck := time.Duration(0)
	for _, name := range tree.InstanceNames() {
		inst, err := resolve.Resolve(o.Cfg, tree, name)
		if err != nil {
			return nil, nil, err
		}
		if len(inst.Missing) == 0 {
			unit, err := quadlet.RenderContainer(inst.Quadlet)
			if err != nil {
				return nil, nil, fmt.Errorf("instance %s: %w", name, err)
			}
			f := File{Dir: Quadlet, Name: inst.Quadlet.Name + ".container", Content: generated(unit)}
			if p := Pending(inst); len(p) > 0 && !o.deploys(name) {
				if _, err := os.Stat(filepath.Join(o.QuadletDir, f.Name)); err == nil {
					f.Hold = true
					warnings = append(warnings, fmt.Sprintf("instance %s: %s pending, its unit keeps the generations it runs until it is restarted", name, strings.Join(p, ", ")))
				}
			}
			files = append(files, f)
		} else {
			warnings = append(warnings, fmt.Sprintf("instance %s is not deployed: %s", name, strings.Join(inst.Missing, "; ")))
		}
		if s := inst.Restarts.Schedule; len(s) > 0 {
			files = append(files, timer(o, "dzo-restart-"+name, "Scheduled restart of "+name, o.cmd("restart", name), s, false)...)
		}
		if s := inst.Backup.Schedule; s != "" {
			files = append(files, timer(o, "dzo-backup-"+name, "Scheduled snapshot of "+name, o.cmd("backup", "create", name, "--reason", "scheduled"), []string{s}, true)...)
		}
		if iv := inst.Updates.CheckInterval.Std(); iv > 0 && (minCheck == 0 || iv < minCheck) {
			minCheck = iv
		}
	}
	if minCheck == 0 {
		minCheck = time.Hour
	}
	files = append(files, timer(o, "dzo-update-check", "Check for mod updates and apply them as the policies allow", o.cmd("update", "check", "--apply"), []string{Calendar(minCheck)}, true)...)
	files = append(files, timer(o, "dzo-backup-prune", "Prune old snapshots", o.cmd("backup", "prune"), []string{"daily"}, true)...)
	files = append(files, timer(o, "dzo-logs", "Rotate the profile logs of all instances", o.cmd("logs", "rotate", "--all"), []string{"hourly"}, true)...)
	status := o.StatusDir
	if status == "" {
		status = "/run/dzo/status"
	}
	files = append(files, timer(o, "dzo-status", "Write the local status snapshot", o.cmd("status", "--write", status), []string{"minutely"}, false)...)
	files = append(files, exporterUnit(o))
	return files, warnings, nil
}

// Result is what a sync did.
type Result struct {
	Written, Removed []string
	Unchanged        int
	Warnings         []string
}

func (o Options) dir(d Dir) string {
	if d == Quadlet {
		return o.QuadletDir
	}
	return o.UnitDir
}

// Sync writes the desired units, removes generated units that are no longer
// desired, records the generations of the deployed instances, and tells
// systemd (daemon-reload, then enable --now for timers and the exporter).
// Instances are never started or stopped by it. With dryRun nothing is
// written.
func Sync(ctx context.Context, o Options, tree *site.Tree, lc instance.Lifecycle, dryRun bool) (Result, error) {
	files, warnings, err := Desired(o, tree)
	res := Result{Warnings: warnings}
	if err != nil {
		return res, err
	}
	want := map[string]bool{}
	for _, f := range files {
		want[filepath.Join(o.dir(f.Dir), f.Name)] = true
	}
	var enable []string
	held := map[string]bool{}
	for _, f := range files {
		path := filepath.Join(o.dir(f.Dir), f.Name)
		if f.Hold {
			res.Unchanged++
			held[strings.TrimSuffix(f.Name, ".container")] = true
			continue
		}
		if old, err := os.ReadFile(path); err == nil && string(old) == f.Content { //nolint:gosec // dzo's own unit dir
			res.Unchanged++
			if f.Enable != "" {
				enable = append(enable, f.Enable)
			}
			continue
		}
		res.Written = append(res.Written, path)
		if f.Enable != "" {
			enable = append(enable, f.Enable)
		}
		if dryRun {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			return res, err
		}
		if err := writeAtomic(path, []byte(f.Content), 0o644); err != nil { //nolint:gosec // unit files are read by systemd
			return res, err
		}
	}
	var gone []string // timers and services to disable
	for _, d := range []Dir{Quadlet, Systemd} {
		es, _ := os.ReadDir(o.dir(d))
		for _, e := range es {
			p := filepath.Join(o.dir(d), e.Name())
			if !strings.HasPrefix(e.Name(), "dzo-") || want[p] || e.IsDir() {
				continue
			}
			if b, err := os.ReadFile(p); err != nil || !strings.HasPrefix(string(b), Header) { //nolint:gosec // dzo's own unit dir
				continue // not ours
			}
			res.Removed = append(res.Removed, p)
			if strings.HasSuffix(e.Name(), ".timer") || strings.HasSuffix(e.Name(), ".service") && d == Systemd {
				gone = append(gone, e.Name())
			}
			if !dryRun {
				if err := os.Remove(p); err != nil {
					return res, err
				}
			}
		}
	}
	if dryRun {
		return res, nil
	}
	for _, name := range tree.InstanceNames() {
		inst, err := resolve.Resolve(o.Cfg, tree, name)
		if err == nil && len(inst.Missing) == 0 && !held["dzo-"+name] {
			if err := Record(inst); err != nil {
				return res, err
			}
		}
	}
	if len(res.Written) > 0 || len(res.Removed) > 0 {
		if err := lc.DaemonReload(ctx); err != nil {
			res.Warnings = append(res.Warnings, "daemon-reload: "+err.Error())
			return res, nil
		}
	}
	if len(gone) > 0 {
		if err := lc.Disable(ctx, gone...); err != nil {
			res.Warnings = append(res.Warnings, "disable: "+err.Error())
		}
	}
	if len(enable) > 0 {
		if err := lc.EnableNow(ctx, enable...); err != nil {
			res.Warnings = append(res.Warnings, "enable: "+err.Error())
		}
	}
	return res, nil
}

func writeAtomic(path string, b []byte, mode os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".unit-*.tmp")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name()) //nolint:errcheck // gone after the rename
	if _, err := tmp.Write(b); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmp.Name(), mode); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
