// SPDX-FileCopyrightText: 2026 Bernd Zeimetz <bernd@bzed.de>
// SPDX-License-Identifier: AGPL-3.0-or-later

package legacy

import (
	"encoding/json"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var passwordRe = regexp.MustCompile(`(?m)^(\s*password(?:Admin)?\s*=\s*)"[^"]+"`)

// scrubPasswords replaces the join and admin passwords of a serverDZ.cfg, which the legacy
// repository kept in git, by a placeholder.
func scrubPasswords(cfg []byte) ([]byte, int) {
	n := len(passwordRe.FindAll(cfg, -1))
	return passwordRe.ReplaceAll(cfg, []byte(`${1}"CHANGE-ME"`)), n
}

var (
	paramsRe   = regexp.MustCompile(`(?m)^\s*parameters="([^"]*)"`)
	portRe     = regexp.MustCompile(`^(\d+):(\d+)`)
	activeLine = regexp.MustCompile(`^(?:[a-z_]+/|\./|/|[A-Za-z_][\w.-]*\s)`) // a command, not an assignment
)

type serverJSON struct {
	Ports       []string          `json:"ports"`
	Volumes     []string          `json:"volumes"`
	Environment map[string]string `json:"environment"`
}

func mapSource(b *branch, template string) (string, string) {
	var ids []string
	for _, e := range b.list {
		if m := idFile.FindStringSubmatch(e.Path); m != nil && m[2] == "map.env" {
			ids = append(ids, e.Path)
		}
	}
	sort.Strings(ids)
	for _, p := range ids {
		env := parseEnv(b.show(p))
		if ok, _ := path.Match(env["MPDIR"], template); ok && env["REPO"] != "" && !strings.HasPrefix(env["MPDIR"], "dayzOffline.") {
			return env["REPO"], env["MPDIR"]
		}
	}
	return "", ""
}

func convertInstance(out map[string][]byte, rep *report, b *branch, o Options) {
	n := b.name
	dir := path.Join("instances", n)
	cfg := b.show("files/serverDZ.cfg")
	if cfg == nil {
		rep.add(n, "files/serverDZ.cfg is missing; the instance is incomplete")
	} else {
		clean, n := scrubPasswords(cfg)
		out[path.Join(dir, "serverDZ.cfg")] = clean
		if n > 0 {
			rep.add(b.name, "serverDZ.cfg: %d password value(s) were replaced by CHANGE-ME; set them (the legacy file had them in git)", n)
		}
	}
	template := parseTemplate(cfg)
	if template == "" {
		rep.add(n, "serverDZ.cfg has no template; set `map:` in instance.yaml")
		template = "dayzOffline.chernarusplus"
	}

	var y strings.Builder
	fmt.Fprintf(&y, "# Generated by dzo legacy convert-config from branch %s. Entries marked \"review\" need a decision.\n", b.ref)
	fmt.Fprintf(&y, "name: %s\nproduct: dayz-stable\nmap: %s\n", n, template)

	// the mission
	if !strings.HasPrefix(template, "dayzOffline.") {
		git, p := mapSource(b, template)
		if git == "" {
			git, p = "https://example.invalid/"+template+".git", template
			rep.add(n, "no map.env provides the mission %q: mission_source is a placeholder, set the repository", template)
			fmt.Fprintf(&y, "mission_source: {git: %s, ref: HEAD, path: %s}  # review: placeholder\n", yamlQuote(git), yamlQuote(p))
		} else {
			fmt.Fprintf(&y, "mission_source: {git: %s, ref: HEAD, path: %s}  # review: the legacy map.env followed the default branch\n", yamlQuote(git), yamlQuote(p))
			rep.add(n, "the mission %s comes from %s (the legacy map.env); ref is HEAD, pin a tag or commit if you want updates to be explicit", template, git)
		}
		fmt.Fprintf(&y, "fallback_mission: dayzOffline.chernarusplus  # review: files the map lacks come from Chernarus, as in the legacy start\n")
	} else {
		rep.add(n, "the mission comes from the default source: the %s folder of Bohemia's Central Economy repository", template)
	}

	// ports
	var sj serverJSON
	if data := b.show("config/containers/server.json"); data != nil {
		if err := json.Unmarshal(data, &sj); err != nil {
			rep.add(n, "config/containers/server.json does not parse: %v", err)
		}
	}
	var ports []int
	for _, p := range sj.Ports {
		if m := portRe.FindStringSubmatch(p); m != nil {
			v, _ := strconv.Atoi(m[1])
			ports = append(ports, v)
		}
	}
	for len(ports) < 3 {
		ports = append(ports, 2302+len(ports))
		rep.add(n, "ports: fewer than three ports in server.json, a default was used; review")
	}
	fmt.Fprintf(&y, "ports: {game: %d, rcon: %d, query: %d}  # review: kept from server.json (game, rcon, query), offset %d\n", ports[0]+o.PortOffset, ports[1]+o.PortOffset, ports[2]+o.PortOffset, o.PortOffset)
	y.WriteString("network: host\n")

	// params
	var cpu string
	var fps string
	var extra []string
	if m := paramsRe.FindSubmatch(b.show("server/bin/dz")); m != nil {
		for _, tok := range strings.Fields(string(m[1])) {
			switch {
			case strings.HasPrefix(tok, "-config="), strings.HasPrefix(tok, "-port="), strings.HasPrefix(tok, "-BEpath="), strings.HasPrefix(tok, "-profiles="):
			case strings.HasPrefix(tok, "-cpuCount="):
				cpu = strings.TrimPrefix(tok, "-cpuCount=")
			case strings.HasPrefix(tok, "-limitFPS="):
				fps = strings.TrimPrefix(tok, "-limitFPS=")
			default:
				extra = append(extra, tok)
			}
		}
	}
	var ps []string
	if cpu != "" {
		ps = append(ps, "cpuCount: "+yamlQuote(cpu))
	}
	if fps != "" {
		ps = append(ps, "limitFPS: "+fps)
	}
	if len(extra) > 0 {
		var q []string
		for _, e := range extra {
			q = append(q, yamlQuote(e))
		}
		ps = append(ps, "extra: ["+strings.Join(q, ", ")+"]")
	}
	if len(ps) > 0 {
		fmt.Fprintf(&y, "params: {%s}\n", strings.Join(ps, ", "))
	}

	// mods
	servermods := map[string]bool{}
	for _, l := range strings.Split(string(b.show("files/servermods")), "\n") {
		if l = strings.TrimSpace(l); l != "" {
			servermods[l] = true
		}
	}
	var ids []uint64
	for id, m := range b.mods {
		if m.name != "" {
			ids = append(ids, id)
		}
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	matched := map[string]bool{}
	if len(ids) > 0 {
		y.WriteString("mods:  # review: the legacy repository does not record which mods were active; every mod it knows is listed\n")
	}
	for _, id := range ids {
		m := b.mods[id]
		srv := ""
		if servermods[m.name] {
			srv = ", server: true"
			matched[m.name] = true
		}
		fmt.Fprintf(&y, "  - {id: %d%s}  # %s\n", id, srv, m.name)
	}
	var unmatched []string
	for s := range servermods {
		if !matched[s] {
			unmatched = append(unmatched, s)
		}
	}
	sort.Strings(unmatched)
	if len(unmatched) > 0 {
		rep.add(n, "files/servermods names that match no workshop mod (local servermods or mods that are not linked): %s", strings.Join(unmatched, ", "))
	}
	rep.add(n, "%d mod(s) listed as candidates; the active set and the order were only in the legacy volumes", len(ids))

	// overlays
	if len(b.overlays) > 0 {
		var ovs []string
		for name := range b.overlays {
			ovs = append(ovs, name)
		}
		sort.Strings(ovs)
		fmt.Fprintf(&y, "overlays: [%s]\n", strings.Join(ovs, ", "))
	}

	// settings that were cron or compose in the legacy system
	y.WriteString("updates: {policy: notify}  # review\n")
	y.WriteString("restarts:\n  schedule: [\"*-*-* 00/4:00\"]  # review: the legacy restart times were cron entries on the host\n")
	rep.add(n, "restart times, update checks and RCon passwords are not in the repository: the defaults in instance.yaml are placeholders")

	// container
	var mounts []string
	logz := ""
	for _, v := range sj.Volumes {
		parts := strings.Split(v, ":")
		if len(parts) < 2 || !strings.HasPrefix(parts[0], "/") {
			continue
		}
		if strings.HasPrefix(parts[1], "/profiles/logz") {
			logz = parts[0]
			continue
		}
		mounts = append(mounts, v)
	}
	if len(mounts) > 0 || logz != "" || len(sj.Environment) > 0 {
		y.WriteString("container:\n")
		if len(sj.Environment) > 0 {
			var keys []string
			for k := range sj.Environment {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			var kv []string
			for _, k := range keys {
				kv = append(kv, k+": "+yamlQuote(sj.Environment[k]))
			}
			fmt.Fprintf(&y, "  env: {%s}\n", strings.Join(kv, ", "))
		}
		if len(mounts) > 0 {
			var q []string
			for _, m := range mounts {
				q = append(q, yamlQuote(m))
			}
			fmt.Fprintf(&y, "  mounts: [%s]\n", strings.Join(q, ", "))
		}
		if logz != "" {
			fmt.Fprintf(&y, "  logz_dir: %s  # review: it was mounted at /profiles/logz/logs in the legacy container\n", logz)
		}
	}

	// messages and hooks
	if msg := b.show("files/messages.xml"); msg != nil {
		out[path.Join(dir, "messages.xml")] = msg
	}
	if pre := b.show("files/bin/pre_start.sh"); pre != nil {
		if hasActiveCommand(pre) {
			out[path.Join(dir, "hooks", "pre_start.sh")] = pre
			for _, h := range []string{"update_dayz_weather"} {
				if data := b.show("files/bin/" + h); data != nil && strings.Contains(string(pre), h) {
					out[path.Join(dir, "hooks", h)] = data
				}
			}
			fmt.Fprintf(&y, "hooks:\n  pre_start: [hooks/pre_start.sh]  # review: the script refers to the legacy container's paths (/files, /serverfiles)\n")
			rep.add(n, "files/bin/pre_start.sh became the pre_start hook; its paths point into the legacy container and need adapting")
		} else {
			rep.add(n, "files/bin/pre_start.sh does nothing active (everything is commented out); dropped")
		}
	}
	out[path.Join(dir, "instance.yaml")] = []byte(y.String())
}

// hasActiveCommand says whether a shell script runs anything besides assignments, mkdir, set and exit.
func hasActiveCommand(s []byte) bool {
	for _, l := range strings.Split(string(s), "\n") {
		l = strings.TrimSpace(l)
		switch {
		case l == "", strings.HasPrefix(l, "#"), strings.HasPrefix(l, "exit"), strings.HasPrefix(l, "set "), strings.HasPrefix(l, "mkdir"):
			continue
		case strings.Contains(l, "=") && !strings.ContainsAny(strings.SplitN(l, "=", 2)[0], " /"):
			continue
		}
		if activeLine.MatchString(l) {
			return true
		}
	}
	return false
}

func renderReport(rep *report, o Options) string {
	var b strings.Builder
	b.WriteString("# Conversion report\n\n")
	fmt.Fprintf(&b, "Generated by `dzo legacy convert-config` from the branches %s. The legacy repository is only a source of\n"+
		"configuration: nothing was read from volumes or hosts, and no live data is converted. Every `# review` comment in an\n"+
		"`instance.yaml` marks a decision that was not made for you.\n\n", strings.Join(o.Refs, ", "))
	b.WriteString("Not converted by design: the active mod set and its order, restart times and update checks (cron on the host), RCon\n" +
		"passwords, Steam credentials and any live state.\n\n")
	order := append([]string{}, rep.order...)
	sort.Slice(order, func(i, j int) bool {
		if (order[i] == "") != (order[j] == "") {
			return order[i] == ""
		}
		return order[i] < order[j]
	})
	for _, s := range order {
		if s == "" {
			b.WriteString("## Shared\n\n")
		} else {
			fmt.Fprintf(&b, "## Instance %s\n\n", s)
		}
		for _, l := range rep.sections[s] {
			fmt.Fprintf(&b, "* %s\n", l)
		}
		b.WriteString("\n")
	}
	return b.String()
}
